import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from '@mui/system';
import theme from "@/app/theme";

// Use Poppins font
const poppins = Poppins({
  weight: [
    '400',
    '500',
    '600',
    '700',
    '800',
    '900'
  ],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body className={poppins.className}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
